insert into Country
values	('AFG', 'Afghanistan'),
		('ALB', 'Albania'),
		('ALG', 'Algeria'),
		('AND', 'Andorra'),
		('ANG', 'Angola'),
		('ARG', 'Argentina'),
		('AUS', 'Australia'),
		('AUT', 'Autriche'),
		('BHS', 'Bahamas'),
		('BGD', 'Bangladesh'),
		('ARM', 'Armenia'),
		('BEL','Belgique'),
		('BHU', 'Bhutan'),
		('BOL', 'Bolivia'),
		('BIH','Bosnie-Herzégovine'),
		('BWA', 'Botswana'),
		('BRA', 'Brazil'),
		('BLZ', 'Belize'),
		('BGR', 'Bulgaria'),
		('BDI', 'Burundi'),
		('KHM', 'Cambodia'),
		('CMR', 'Cameroon'),
		('CAN', 'Canada'),
		('CPV', 'Cape Verde'),
		('CYM', 'Cayman Islands'),
		('CAF', 'Central African'),
		('LKA', 'Sri Lanka'),
		('TCD', 'Chad'),
		('CHL', 'Chile'),
		('CHN', 'China'),
		('TWN', 'Taiwan'),
		('CXR', 'Christmas Island'),
		('COL', 'Colombia'),
		('COM', 'Comoros'),
		('MYT', 'Mayotte'),
		('COG', 'Republic of the Congo'),
		('COD', 'The Democratic Republic Of The Congo'),
		('COK', 'Cook Islands'),
		('CRI', 'Costa Rica'),
		('HRV', 'Croatia'),
		('CUB', 'Cuba'),
		('CYP', 'Cyprus'),
		('CZE', 'Czech Republic'),
		('BEN', 'Benin'),
		('DNK', 'Denmark'),
		('DOM', 'Dominican Republic'),
		('ECU', 'Ecuador'),
		('GNQ', 'Equatorial Guinea'),
		('ETH', 'Ethiopia'),
		('ERI', 'Eritrea'),
		('EST', 'Estonia'),
		('FRO', 'Faroe Islands'),
		('SGS', 'South Georgia'),
		('FJI', 'Fiji'),
		('FIN', 'Finland'),
		('FRA','France'),
		('GUF', 'French Guiana'),
		('PYF', 'French Polynesia'),
		('DJI', 'Djibouti'),
		('GAB', 'Gabon'),
		('GEO', 'Georgia'),
		('GMB', 'Gambia'),
		('DEU', 'Germany'),
		('GHA', 'Ghana'),
		('GIB', 'Gibraltar'),
		('KIR', 'Kiribati'),
		('GRC', 'Greece'),
		('GRL', 'Greenland'),
		('GRD', 'Grenada'),
		('GLP', 'Guadeloupe'),
		('GUM', 'Guam'),
		('GTM', 'Guatemala'),
		('GIN', 'Guinea'),
		('GUY', 'Guyana'),
		('HTI', 'Haiti'),
		('VAT', 'Vatican City State'),
		('HND', 'Honduras'),
		('HKG', 'Hong Kong'),
		('HUN', 'Hungary'),
		('ISL', 'Iceland'),
		('IND', 'India'),
		('IDN', 'Indonesia'),
		('IRN', 'Islamic Republic of Iran'),
		('IRQ', 'Iraq'),
		('IRL', 'Ireland'),
		('ISR', 'Israel'),
		('ITA', 'Italy'),
		('CIV', 'Côte d''Ivoire'),
		('JAM', 'Jamaica'),
		('JPN', 'Japan'),
		('KAZ', 'Kazakhstan'),
		('JOR', 'Jordan'),
		('KEN', 'Kenya'),
		('PRK', 'Democratic People''s Republic of Korea'),
		('KOR', 'Republic of Korea'),
		('KWT', 'Kuwait'),
		('KGZ', 'Kyrgyzstan'),
		('LBN', 'Lebanon'),
		('LVA', 'Latvia'),
		('LBR', 'Liberia'),
		('LIE', 'Liechtenstein'),
		('LTU', 'Lithuania'),
		('LUX', 'Luxembourg'),
		('MAC', 'Macao'),
		('MDG', 'Madagascar'),
		('MWI', 'Malawi'),
		('MYS', 'Malaysia'),
		('MDV', 'Maldives'),
		('MLI', 'Mali'),
		('MLT', 'Malta'),
		('MTQ', 'Martinique'),
		('MUS', 'Mauritius'),
		('MEX', 'Mexico'),
		('MCO', 'Monaco'),
		('MNG', 'Mongolia'),
		('MAR', 'Morocco'),
		('MOZ', 'Mozambique'),
		('OMN', 'Oman'),
		('NAM', 'Namibia'),
		('NRU', 'Nauru'),
		('NPL', 'Nepal'),
		('NLD', 'Netherlands'),
		('ANT', 'Netherlands Antilles'),
		('ABW', 'Aruba'),
		('NCL', 'New Caledonia'),
		('VUT', 'Vanuatu'),
		('NZL', 'New Zealand'),
		('NIC', 'Nicaragua'),
		('NER', 'Niger'),
		('NGA', 'Nigeria'),
		('NIU', 'Niue'),
		('NOR', 'Norway'),
		('PAK', 'Pakistan'),
		('PAN', 'Panama'),
		('PNG', 'Papua New Guinea'),
		('PRY', 'Paraguay'),
		('PER', 'Peru'),
		('PHL', 'Philippines'),
		('POL', 'Poland'),
		('PRT', 'Portugal'),
		('PRI', 'Puerto Rico'),
		('QAT', 'Qatar'),
		('REU', 'Réunion'),
		('ROU', 'Romania'),
		('RUS', 'Russian Federation'),
		('RWA', 'Rwanda'),
		('SHN', 'Saint Helena'),
		('AIA', 'Anguilla'),
		('SAU', 'Saudi Arabia'),
		('SEN', 'Senegal'),
		('SYC', 'Seychelles'),
		('SGP', 'Singapore'),
		('SVK', 'Slovakia'),
		('VNM', 'Vietnam'),
		('SVN', 'Slovenia'),
		('SOM', 'Somalia'),
		('ZAF', 'South Africa'),
		('ZWE', 'Zimbabwe'),
		('ESP', 'Spain'),
		('SDN', 'Sudan'),
		('SWE', 'Sweden'),
		('CHE', 'Switzerland'),
		('TJK', 'Tajikistan'),
		('THA', 'Thailand'),
		('TGO', 'Togo'),
		('TON', 'Tonga'),
		('ARE', 'United Arab Emirates'),
		('TUN', 'Tunisia'),
		('TUR', 'Turkey'),
		('TKM', 'Turkmenistan'),
		('UGA', 'Uganda'),
		('UKR', 'Ukraine'),
		('EGY', 'Egypt'),
		('GBR', 'United Kingdom'),
		('TZA', 'United Republic Of Tanzania'),
		('USA', 'United States'),
		('VIR', 'U.S. Virgin Islands'),
		('URY', 'Uruguay'),
		('UZB', 'Uzbekistan'),
		('VEN', 'Venezuela'),
		('WSM', 'Samoa'),
		('YEM', 'Yemen'),
		('SCG', 'Serbia and Montenegro'),
		('ZMB', 'Zambia');